<?

  require_once('../assets/func/global.func.php');

  $_sql = DB::query("SELECT event_uid, event_name, event_venue, event_sdate, event_edate, event_stime, event_etime, event_cover, event_category, event_description, autogenerated FROM `uniparti_events` ORDER BY `event_sdate`");

?>
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- title -->
    <title>uniparti [events]</title>

    <!-- meta -->
    <meta charset="utf-8">
    <meta name="description" content="UniParti is a community-reliant event website that provides all the latest and upcoming events in your area.">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- twitter meta -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Uniparti">
    <meta name="twitter:image" content="https://uniparti.com/assets/css/img/meta.jpg">
    <meta name="twitter:image:alt" content="https://uniparti.com/assets/css/img/meta.jpg">

    <!-- facebook meta -->
    <meta property="og:url" content="https://uniparti.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Uniparti" />
    <meta property="og:image" content="https://uniparti.com/assets/css/img/meta.jpg" />

    <!-- style -->
    <link rel="shortcut icon" href="https://uniparti.com/favicon.ico">
    <link rel="stylesheet" href="https://uniparti.com/assets/css/style.css" />
    <link rel="stylesheet" href="https://uniparti.com/assets/css/style_events.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  </head>
  <body>

    <!-- preloader -->
    <div class="preloader" id="pre-loader"></div>

    <div class="navigation-container" id="navigation-container">
      <div class="col-12">
        <div class="col-4">
          <div class="brand-section">
            <div class="logo"></div>
            <a href="https://uniparti.com" class="title underline">uniparti</a>
          </div>
        </div>
        <div class="col-8">
          <ul class="navigation-list">
            <li class="navigation-list-item"><a href="https://uniparti.com">home</a></li>
            <li class="navigation-list-item active"><a href="">events</a></li>
            <li class="navigation-list-item"><a href="https://uniparti.com/news/">news</a></li>
            <li class="navigation-list-item"><a href="https://uniparti.com/contact/">contact us</a></li>
            <li class="navigation-list-item post-event"><a href="https://uniparti.com/create/">post an event</a></li>
          </ul>
        </div>
      </div>
    </div>

    <!-- mobile menu -->
    <div id="mobile-menu" class="mobile-menu">
      <div id="mobile_symbol" class="mobile_symbol"><i class="fas fa-bars"></i></div>

      <!-- mobile menu list -->
      <ul id="mobile_menu_list" class="mobile_menu_list">
        <li><a href="https://uniparti.com">home</a></li>
        <li><a href="">events</a></li>
        <li><a href="https://uniparti.com/news/">news</a></li>
        <li><a href="https://uniparti.com/contact/">contact us</a></li>
        <li><a href="https://uniparti.com/create/">post an event</a></li>
      </ul>
      <!-- ! [mobile menu list] -->
    </div>
    <!-- ! [mobile menu] -->

    <div class="wrapper">

      <!-- events -->
      <div class="col-10">

        <!-- categories -->
        <div class="col-12">
          <ul class="event-categories">
            <label>categories:</label>
            <li category="all" class="category underline active">all</li>
            <li category="fundraiser" class="category underline">fundraiser</li>
            <li category="workshop" class="category underline">workshop</li>
            <li category="seminar" class="category underline">seminar</li>
            <li category="rso-meeting" class="category underline">rso meeting</li>
            <li category="celebration" class="category underline">celebration</li>
            <li category="other" class="category underline">other</li>
          </ul>
        </div>
        <!-- ! [categories] -->

        <!-- event list -->
        <div class="col-12">

          <?php

          $x = 1;
          while($row = $_sql->fetch()) {

            $row['event_cover'] = ($row['event_cover']) ? $row['event_cover'] : "blank_cover.jpg";
            $date_string = date("l, F j, Y", $row['event_sdate']);
            $autogenerated = ($row['autogenerated']) ? "<div class=\"event-item-auto-generated\">auto-generated by uniparti</div>" : "";

            echo "
              <!-- event item -->
              <div class=\"col-3 event-item\" category=\"{$row['event_category']}\" id=\"event-item-{$x}\" event-id=\"{$row['event_uid']}\">
                <a href=\"https://uniparti.com/events/{$row['event_uid']}/\">
                  <div class=\"event-item-image-section\" style=\"background:url('https://uniparti.com/events/cover/{$row['event_cover']}') center center / cover no-repeat;\">{$autogenerated}</div>
                  <div class=\"event-item-information-section\">
                    <div class=\"event-item-title-section\">{$row['event_name']}</div>
                    <div class=\"event-item-date-section\">{$date_string}</div>
                  </div>
                </a>
              </div>
              <!-- ! [event item] -->
            ";

            $x++;

          }

          ?>

        </div>
        <!-- ! [event list] -->

        <!-- controls -->
        <div class="col-12">
          <div class="pagination-controls">
            <p id="pages"></p>
          </div>
        </div>
        <!-- ! [controls] -->

      </div>
      <!-- ! [events] -->

      <!-- spacer -->
      <div class="col-12">
        <div class="spacer-section two">
          <div class="spacer-text">
            <p id="spacer-text">thanks for joining us</p>
          </div>
        </div>
      </div>
      <!-- ! [spacer] -->

    </div>
    <!-- ! [wrapper] -->

    <!-- footer -->
    <div class="col-12">
      <div class="footer">
        <div class="col-12">
          <div class="col-4">
            <div class="social-links">
               <?=$language_array['social_links']?>
            </div>
          </div>
          <div class="col-5">
            <div class="copyright">
              <p><?=$language_array['copyright']?></p>
            </div>
          </div>
          <div class="col-3">
            <div class="brand-section">
              <a href="" class="title underline">uniparti</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ! [footer] -->

  <!-- Scripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>var index_page = false;</script>
  <script src="https://uniparti.com/assets/js/global.js"></script>
  <script src="https://uniparti.com/assets/js/events.js"></script>
  </body>
</html>
